name: SSH Server Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
   
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          private-key: ${{ secrets.SERVER_SSH_KEY }}
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v3
        with:
         
         
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          scp_source: /*
          scp_target: ${{ secrets.SCP_TARGET }}
          before_script: |
            
          after_script: |
            npm install
